export const PACKAGE_LIST_REQUEST = 'PACKAGE_LIST_REQUEST'
export const PACKAGE_LIST_SUCCESS = 'PACKAGE_LIST_SUCCESS'
export const PACKAGE_LIST_FAIL = 'PACKAGE_LIST_FAIL'


export const PACKAGE_DETAIL_REQUEST = 'PACKAGE_DETAIL_REQUEST'
export const PACKAGE_DETAIL_SUCCESS = 'PACKAGE_DETAIL_SUCCESS'
export const PACKAGE_DETAIL_FAIL = 'PACKAGE_DETAIL_FAIL'


export const PACKAGE_DELETE_REQUEST = 'PACKAGE_DELETE_REQUEST';
export const PACKAGE_DELETE_SUCCESS = 'PACKAGE_DELETE_SUCCESS';
export const PACKAGE_DELETE_FAIL = 'PACKAGE_DELETE_FAIL';
