export const QUERY_LIST_REQUEST = 'QUERY_LIST_REQUEST';
export const QUERY_LIST_SUCCESS = 'QUERY_LIST_SUCCESS';
export const QUERY_LIST_FAIL = 'QUERY_LIST_FAIL';
export const QUERY_LIST_RESET = 'QUERY_LIST_RESET';