export const QUERY_LIST_REQUEST = 'QUERY_LIST_REQUEST';
export const QUERY_LIST_SUCCESS = 'QUERY_LIST_SUCCESS';
export const QUERY_LIST_FAIL = 'QUERY_LIST_FAIL';
export const QUERY_LIST_RESET = 'QUERY_LIST_RESET';


export const QUERY_MY_LIST_REQUEST = 'QUERY_MY_LIST_REQUEST';
export const QUERY_MY_LIST_SUCCESS = 'QUERY_MY_LIST_SUCCESS';
export const QUERY_MY_LIST_FAIL = 'QUERY_MY_LIST_FAIL';
export const QUERY_MY_LIST_RESET = 'QUERY_MY_LIST_RESET';

export const QUERY_ANONYMOUS_MY_LIST_REQUEST = 'QUERY_ANONYMOUS_MY_LIST_REQUEST';
export const QUERY_ANONYMOUS_MY_LIST_SUCCESS = 'QUERY_ANONYMOUS_MY_LIST_SUCCESS';
export const QUERY_ANONYMOUS_MY_LIST_FAIL = 'QUERY_ANONYMOUS_MY_LIST_FAIL';
export const QUERY_ANONYMOUS_MY_LIST_RESET = 'QUERY_ANONYMOUS_MY_LIST_RESET';


export const QUERY_RESPOND_REQUEST = 'QUERY_RESPOND_REQUEST';
export const QUERY_RESPOND_SUCCESS = 'QUERY_RESPOND_SUCCESS';
export const QUERY_RESPOND_FAIL = 'QUERY_RESPOND_FAIL';
